apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: toplard/my-flask-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "postgresql://api_user:securepassword123@postgres-service:5432/flask_api_db"