apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
  namespace: default
spec:
  selector:
    app: flask-api
  ports:
  - protocol: TCP
    port: 80  # External port
    targetPort: 5000  # Container port
  type: ClusterIP  # Internal service