apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: default
spec:
  replicas: 2  # Run 2 pods for redundancy
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: toplard/my-flask-api:latest  # Use your image name
        imagePullPolicy: Always  # Use local image
        ports:
        - containerPort: 5000