apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce  # Single pod can read/write
  resources:
    requests:
      storage: 1Gi  # 1GB of storage
  storageClassName: microk8s-hostpath