apiVersion: apps/v1
kind: Deployment
metadata:
  name: topman
spec:
  replicas: 3
  selector:
    matchLabels:
      app: topman
  template:
    metadata:
      labels:
        app: topman
    spec:
      containers:
      - name: topman
        image: nginx:latest
        ports:
        - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: topman
spec:
  selector:
    app: topman
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP 